# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "COLOR=blue" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.COLOR }}"

  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
            echo "SENTENCE='Hello world'" >> $GITHUB_OUTPUT
    outputs:
        produced_output: ${{ steps.sentence_maker.outputs.SENTENCE }}

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - name: Print the message
        run: |
          echo "The message is ${{ needs.producer.outputs.produced_output }}"

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: final
          path: artifact.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: final
      - shell: bash
        run: |
          value=`cat artifact.txt`
          echo $(expr $value \* 9)
